# Generated by Django 4.2.6 on 2023-11-25 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("phone", models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("phone", models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip", models.IntegerField()),
                ("state", models.CharField(max_length=2)),
                ("address", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                ("desciption", models.TextField()),
                ("ownerName", models.TextField()),
                ("propertyID", models.IntegerField()),
                (
                    "agentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allAssignedProperties",
                        to="real_estate.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.IntegerField()),
                ("password", models.TextField()),
                ("username", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("comment", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="myReviews",
                        to="real_estate.customer",
                    ),
                ),
                (
                    "propertyID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allReviews",
                        to="real_estate.property",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="customerID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isCutomer",
                to="real_estate.user",
            ),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "companyID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isCompany",
                        to="real_estate.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "customerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="myAppointments",
                        to="real_estate.customer",
                    ),
                ),
                (
                    "propertyID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allBookings",
                        to="real_estate.property",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agent",
            name="agentID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isAgent",
                to="real_estate.user",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="companyID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allAgents",
                to="real_estate.company",
            ),
        ),
    ]
