# Generated by Django 5.0 on 2023-12-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(),
        ),
    ]
