# Generated by Django 5.0 on 2023-12-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0002_alter_booking_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="desciption",
            new_name="description",
        ),
    ]
