# Generated by Django 5.0 on 2023-12-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0003_rename_desciption_property_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
